source 'https://rubygems.org'
source 'https://rails-assets.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressoAuthorizationr for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# A Ruby framework for rapid API development with great conventions
gem 'grape'
# Provides Haml generators for Rails 3. It also enables Haml as the templating engine.
gem 'haml-rails'
# CoffeeScript adapter for the Rails asset pipeline. 
gem 'coffee-rails'
# Twitter's Bootstrap, converted to Sass and ready to drop into Rails or Compass
gem 'bootstrap-sass'
# Flexible authentication solution for Rails with Warden
gem 'devise'
# New wave Internationalization support for Ruby.
gem 'rails-i18n'
# assets bower repo comming from 'https://rails-assets.org'
gem 'rails-assets-lodash'
gem 'rails-assets-angular', '~> 1.2.0'
gem 'rails-assets-angular-cache', '~> 2.3.4'
gem 'rails-assets-angular-ui-router', '~> 0.2.9'
gem 'rails-assets-angular-route'
gem 'rails-assets-angular-translate'
gem 'rails-assets-angular-bootstrap'
gem 'rails-assets-angular-resource'

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'factory_girl_rails' 
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :test do 
  gem 'ammeter' # A gem that makes it easy to write specs for your Rails 3 Generators.
  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy' 
end